-- Query to display the number of tickets used and the amount generated by month
-- To know the amount, we use the average price of a ticket following the pack the user choosed to pay his ticket
select DATE_FORMAT(ticket_log.`date`,'%Y-%m'), 
      sum(nb_ticket), 
      round(sum(nb_ticket*pack_tarif_moyen.tarif_ticket),2) 
from ticket_log
inner join commandes on ticket_log.commande_id = commandes.id
inner join users on commandes.user_id = users.id
inner join pack_tarif_moyen on commandes.pack_id = pack_tarif_moyen.id_pack
where commandes.`date` between pack_tarif_moyen.date_debut and pack_tarif_moyen.date_fin
group by DATE_FORMAT(ticket_log.`date`,'%Y-%m')
order by DATE_FORMAT(ticket_log.`date`,'%Y-%m') desc;